### ISSUE TITLE
Trades tab: optional commission/fee columns + add/edit on trade detail page

### ISSUE THREAD

**Issue by EricBell** [EricBell/trading-journal#52]
## Context
Part of #49. User-facing ask: on `/trades`, optionally show/hide Commission and Fee columns; on `/trades/<id>`, allow adding/editing commission and fee values directly (needed regardless of whether ingest-time capture ever lands for a given broker/asset class, since at minimum equities/options data has no confirmed source per #51).

This issue is blocked on the schema landing (commission/fees columns on `trades`, per #49's Phase 1) — scope below assumes that dependency is resolved first.

## Scope

**Trades list (`/trades`, `trades/index.html` + `routes/trades.py`)**
- No column-visibility toggle mechanism exists in this template today (checked directly) — this is net-new UI, not extending an existing pattern.
- Add a simple show/hide control (e.g. a small dropdown/checkbox group in the toolbar area near the existing filters) for "Commission" and "Fees" columns. Persist the choice the same way `per_page` is persisted in `session` today (per OVERVIEW.md's Trades list feature row), so it survives navigation/pagination like the account filter does.
- When shown, render per-completed-trade aggregate commission/fee (sum across the executions that make up that round trip), consistent with how other aggregate figures (`entry_avg_price`, `net_pnl`) are already derived Tier 2 values.

**Trade detail (`/trades/<id>`, `trades/detail.html` + `routes/trades.py`)**
- Add Commission and Fees to the Executions table (currently Time/Side/Qty/Price only, `detail.html` line ~194) so each fill's captured or entered value is visible per-leg, not just as one aggregate.
- Add/edit UI: follow the existing `Stop` field's pattern (`set_stop` — a small inline form posting to its own route, `detail.html` ~line 165) rather than folding editable fields into the derived `completed_trades` row. This matters architecturally: Tier 2 (`completed_trades`) is fully derived and gets destroyed/rebuilt on reprocessing (OVERVIEW.md §3), so a value edited there would silently vanish on the next `db process-trades` run or re-upload touching that symbol. Editing on the Tier 1 `trades` execution rows (which are never recalculated) is durable across rebuilds the same way raw fill data always is.
- Needs a new route, e.g. `POST /trades/<id>/executions/<execution_id>/costs`, updating `trades.commission`/`trades.fees` for that specific execution row.

## Open design question
Manual entry at the execution (Tier 1) level is the architecturally consistent choice, but is more clicks than editing one aggregate value per completed trade. Worth confirming with the user before implementation whether they'd rather:
(a) edit per-execution (durable, more granular, more clicks), or
(b) edit one aggregate figure per completed trade, stored somewhere that survives Tier 2 rebuilds — e.g. a new column on `trade_annotations` (already proven to survive `completed_trades` rebuilds via the natural-key re-link pattern in OVERVIEW.md §5), distributed across executions only at display/calculation time.
This should be settled before implementation starts, not decided unilaterally mid-build.

## Non-goals
- Does not change `net_pnl`/dashboard calculations to net out these values — deferred per #49 Phase 4.
- Does not implement ingest-time capture — depends on #50 and #51, but doesn't block on either landing first since manual entry works independently.

## Verification
- Toggle commission/fee columns on/off on `/trades`; setting persists across pagination and a page reload within the session.
- On a trade detail page, add a commission value to one execution; confirm it displays on both the detail page and (aggregated) on the trades list.
- Edit an existing value; confirm it updates.
- Re-run `db process-trades` / re-upload a file touching that symbol; confirm the manually entered value survives the `completed_trades` rebuild (this is the key architectural check).
